// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psemlpmxtacmpnilibct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzZW1scG14dGFjbXBuaWxpYmN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNzg1NjMsImV4cCI6MjA1Nzk1NDU2M30.DLs-l6a8XaDKGh8lNSzsApsR2CQ_fzDYawPT0Rd-Fo4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);